[workspace]
members = [
    "magritte",
    "magritte-vkgen",
    "magritte-vma",
    "magritte-shaders",
    "magritte-gc",
    "samples",
]

[profile.release]
# Enabling debug symbols for `flamegraph` and `perf`.
debug = true