[workspace]
members = [
    "crates/magritte-parse",
    "crates/magritte-common",
    "crates/magritte-types",
    "bins/magritte-ron-build",
    "bins/magritte-doc-build",
    "magritte-build",
    "magritte",
]

[profile.release]
debug = true