[package]
name = "magritte-hl"
version = "0.1.0"
edition = "2021"

[dependencies]
# Vulkan Memory Allocator
magritte-vma = { path = "../magritte-vma" }

# Vulkan bindings
[dependencies.magritte]
path = "../magritte"
features = [
    "window",
    "validation",
]