[package]
name = "magritte-ron-build"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.32", features = ["derive"] }
magritte-parse = { version = "0.1.0", path = "../../crates/magritte-parse" }
ron = "0.8.0"
serde = "1.0.152"
