[package]
name = "magritte-shaders"
version = "0.1.0"
edition = "2021"

[dependencies]
# Shader compiler
shaderc = "0.8.1"

# Code generation
proc-macro2 = "1.0.49"
quote = "1.0.23"

# SPIR-V reflection