[package]
name = "magritte-gc"
version = "0.1.0"
edition = "2021"

[dependencies]
magritte = { path = "../magritte" }

magritte-vma = { path = "../magritte-vma" }

magritte-hl = { path = "../magritte-hl" }