[package]
name = "magritte-common"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.12.3", optional = true }
serde = { version = "1.0.152", features = ["derive"], optional = true }
